style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG

options:
  commits:
    # filters:
    #   Type:
    #     - feat
    #     - fix
    #     - perf
    #     - refactor
  commit_groups:
    sort_by: Custom
    title_order:
        - feat
        - update
        - perf
        - fix
        - refactor
        - docs
        - build
        - chore
        - ci
    title_maps:
      feat: Features ✨
      fix: Bug Fixes 🐛
      perf: Performance Improvements ⚡
      refactor: Code Refactoring ♻
      update: Updates 🔄
      build: Build 👷
      ci: Continuous Integration 🔄
      chore: Other changes
      docs: Documentation 📖
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE